blueprint:
  name: Gate Pro
  description: >
    Gestisce apertura cancello, allarme, tapparelle, luci e automazioni extra
    al rientro o all'uscita, e quando nessuno è in casa (es. vacanza, serata fuori).
    Notifiche interattive supportate (Android/iOS).
  domain: automation

  input:
    persona_principale:
      name: Persona principale
      selector:
        entity:
          domain: person

    persona_secondaria:
      name: Persona secondaria
      selector:
        entity:
          domain: person

    persone_da_monitorare:
      name: Persone da considerare assenti
      description: >
        Se tutte queste persone non sono in casa per almeno 2 minuti, si attiva lo scenario "Casa Vuota".
      selector:
        entity:
          domain: person
          multiple: true

    tracker_persona:
      name: Tracker GPS della persona principale
      selector:
        entity:
          domain: device_tracker

    trigger_auto:
      name: Sensore accensione auto (opzionale)
      default: []
      selector:
        entity:
          domain: binary_sensor

    cancello_remote:
      name: Telecomando cancello (opzionale)
      default: []
      selector:
        entity:
          domain: remote

    cancello_device_name:
      name: Nome dispositivo Broadlink (es. 'cancello')
      default: "cancello"
      selector:
        text:

    cancello_command:
      name: Comando apertura cancello
      default: apri
      selector:
        text: {}

    allarme:
      name: Pannello allarme (opzionale)
      default: []
      selector:
        entity:
          domain: alarm_control_panel

    codice_allarme:
      name: Codice allarme (opzionale)
      default: ""
      selector:
        text:
          type: password

    tapparelle:
      name: Tapparelle da gestire (opzionale)
      default: []
      selector:
        entity:
          domain: cover
          multiple: true

    luci_accendere:
      name: Luci da accendere (opzionale)
      default: []
      selector:
        entity:
          domain: light
          multiple: true

    luci_spegnere:
      name: Luci da spegnere (opzionale)
      default: []
      selector:
        entity:
          domain: light
          multiple: true

    automazioni_extra:
      name: Automazioni o script aggiuntivi (opzionale)
      default: []
      selector:
        entity:
          domain:
            - automation
            - script
          multiple: true

    sensore_porte:
      name: Sensore conteggio porte aperte (opzionale)
      default: []
      selector:
        entity:
          domain: sensor

    sensore_finestre:
      name: Sensore conteggio finestre aperte (opzionale)
      default: []
      selector:
        entity:
          domain: sensor

    notifiche_interattive_dispositivi:
      name: Dispositivi per notifiche interattive
      description: >
        Seleziona uno o più dispositivi (iOS/Android) su cui inviare notifiche personalizzate.
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    notifiche_interattive_testo:
      name: Messaggio di notifica
      default: "Casa vuota: allarme inserito, tapparelle chiuse, luci gestite."
      selector:
        text: {}

    notifiche_interattive_bottone_titolo:
      name: Titolo pulsante notifica (opzionale)
      default: ""
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input trigger_auto
    to: "on"
    id: partenza_auto

  - platform: zone
    entity_id: !input tracker_persona
    zone: zone.home
    event: enter
    id: rientro

  - platform: zone
    entity_id: !input tracker_persona
    zone: zone.home
    event: leave
    id: uscita

  - platform: state
    entity_id: !input persone_da_monitorare
    from: "home"
    to: "not_home"
    for:
      minutes: 2
    id: nessuno_a_casa

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - partenza_auto
              - uscita
          - condition: state
            entity_id: !input persona_principale
            state: not_home
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ cancello_remote | length > 0 }}"
                sequence:
                  - service: remote.send_command
                    target:
                      entity_id: !input cancello_remote
                    data:
                      device: !input cancello_device_name
                      command: !input cancello_command

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ allarme | length > 0 }}"
                sequence:
                  - service: alarm_control_panel.alarm_arm_away
                    target:
                      entity_id: !input allarme
                    data:
                      code: !input codice_allarme

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ tapparelle | length > 0 }}"
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input tapparelle

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ luci_spegnere | length > 0 }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input luci_spegnere

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ luci_accendere | length > 0 }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input luci_accendere

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ automazioni_extra | length > 0 }}"
                sequence:
                  - service: homeassistant.turn_on
                    target:
                      entity_id: !input automazioni_extra

      - conditions:
          - condition: trigger
            id: rientro
          - condition: state
            entity_id: !input persona_principale
            state: home
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ cancello_remote | length > 0 }}"
                sequence:
                  - service: remote.send_command
                    target:
                      entity_id: !input cancello_remote
                    data:
                      device: !input cancello_device_name
                      command: !input cancello_command

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ tapparelle | length > 0 }}"
                sequence:
                  - service: cover.open_cover
                    target:
                      entity_id: !input tapparelle

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ luci_accendere | length > 0 }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input luci_accendere

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ allarme | length > 0 }}"
                sequence:
                  - service: alarm_control_panel.alarm_disarm
                    target:
                      entity_id: !input allarme
                    data:
                      code: !input codice_allarme

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ automazioni_extra | length > 0 }}"
                sequence:
                  - service: homeassistant.turn_on
                    target:
                      entity_id: !input automazioni_extra

      - conditions:
          - condition: trigger
            id: nessuno_a_casa
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ sensore_porte | length == 0 }}"
              - condition: numeric_state
                entity_id: !input sensore_porte
                below: 1
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ sensore_finestre | length == 0 }}"
              - condition: numeric_state
                entity_id: !input sensore_finestre
                below: 1
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ allarme | length > 0 }}"
                sequence:
                  - service: alarm_control_panel.alarm_arm_away
                    target:
                      entity_id: !input allarme
                    data:
                      code: !input codice_allarme

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ tapparelle | length > 0 }}"
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input tapparelle

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ luci_spegnere | length > 0 }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input luci_spegnere

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ luci_accendere | length > 0 }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input luci_accendere

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ automazioni_extra | length > 0 }}"
                sequence:
                  - service: homeassistant.turn_on
                    target:
                      entity_id: !input automazioni_extra

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notifiche_interattive_dispositivi | length > 0 }}"
                sequence:
                  - repeat:
                      for_each: !input notifiche_interattive_dispositivi
                      sequence:
                        - choose:
                            - conditions:
                                - condition: template
                                  value_template: "{{ notifiche_interattive_bottone_titolo != '' }}"
                              sequence:
                                - service: notify.mobile_app
                                  data:
                                    target: "{{ repeat.item }}"
                                    title: Casa vuota
                                    message: !input notifiche_interattive_testo
                                    data:
                                      actions:
                                        - action: "custom_home_alarm_action"
                                          title: !input notifiche_interattive_bottone_titolo
                          default:
                            - service: notify.mobile_app
                              data:
                                target: "{{ repeat.item }}"
                                title: Casa vuota
                                message: !input notifiche_interattive_testo

mode: single